import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as React from "react";
import sha256 from "crypto-js/sha256";
import router, { useRouter } from "next/router";

const Home: NextPage = () => {
    const router = useRouter();
    const [crushName, setCrushName] = React.useState<string>("");
    const [crushHash, setCrushHash] = React.useState<string>("");

    const { hash, name } = router.query;

    const checkIfCrush = React.useCallback(() => {
        const newCrushHash = sha256(crushName).toString();
        setCrushHash(newCrushHash);
    }, [crushName]);

    const isMatch = React.useMemo(() => hash === crushHash, [crushHash]);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>zk-Crush</h1>

                <h3 className="font-bold">How this works</h3>
                <p>
                    Hello! You may be {name}&apos;s crush! Enter your name below to see if the sha256 hash of your name
                    matches below!
                </p>
                <p>
                    Hash of {name}&apos;s crush: {hash}
                </p>

                <div className={styles.containerPadding}>
                    <p>Your name (first & last)</p>
                    <div className="py-2"></div>
                    <input
                        placeholder="Alice Jones"
                        value={crushName}
                        onChange={(evt) => setCrushName(evt.target.value)}
                    />
                    <div className="py-2"></div>
                    <button onClick={checkIfCrush}>Check match</button>
                    {crushHash && (
                        <p>
                            Your hash is {crushHash}, it&apos;s a {isMatch ? "match!" : "not a match :("}
                        </p>
                    )}
                </div>
            </main>

            <footer className={styles.footer}>
                Built my Amir
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
