import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as React from "react";
import sha256 from "crypto-js/sha256";

const Home: NextPage = () => {
    const [name, setName] = React.useState<string>("");
    const [crushName, setCrushName] = React.useState<string>("");
    const [savedURL, setSavedURL] = React.useState<string>("");

    const generateUrl = React.useCallback(() => {
        const hash = sha256(crushName).toString();
        setSavedURL(
            (process.env.NODE_ENV === "development" ? "http://localhost:3000/" : "https://areyoumycrush.xyz/") +
                `crush?hash=${hash}&name=${name}`
        );
    }, [crushName]);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>zk-Crush ❤️ </h1>

                <h3 className="font-bold">How this works</h3>
                <p>
                    You enter the name of your crush, we will hash it with the sha256 function and generate a unique
                    link that you can share publicly. People can enter their names into this unique link, if the
                    generated hash matches, they'll be notified they are your crush, if not, they will be told they're
                    not and no other info is revealed. Note we do not store any info, this app is entirely client side.
                </p>

                <div className={styles.containerPadding}>
                    <p>Your name</p>
                    <div className="py-2"></div>
                    <input placeholder="Bob" value={name} onChange={(evt) => setName(evt.target.value)} />
                </div>
                <div className={styles.containerPadding}>
                    <p>Name of your crush (first and last)</p>
                    <div className="py-2"></div>
                    <input
                        placeholder="Alice Jones"
                        value={crushName}
                        onChange={(evt) => setCrushName(evt.target.value)}
                    />
                </div>
                <div className={styles.containerPadding}>
                    <button onClick={generateUrl}>Generate URL</button>
                    <p>{savedURL}</p>
                </div>
            </main>

            <footer className={styles.footer}>
                Built my
                <a href="https://twitter.com/amirbolous">Amir</a> and open source on Github
            </footer>
        </div>
    );
};

export default Home;
